### ISSUE TITLE
linkinfo plugin will expand very large title texts and be forced to quit IRC (excess flood)

### ISSUE THREAD

**Issue by danieljabailey** [HackSoc/csbot#150]
Oopsie, I broke it :blush: 
http://9net.org/screenshots/hexchat_2019-04-09_20-11-34.png

**Comment by danieljabailey** [comment]
Ah, ahahah, ah...
https://github.com/HackSoc/csbot/blob/master/csbot/irc.py#L218
...you saw me coming. ;P

**Comment by alanbriolat** [comment]
Was there some other context for this happening? Or can you tell me how long the title was?

I can't reproduce the issue (using https://ersa.hexi.co/~alan/long-title.html); the bot sends one very long message to the server, and the server sends other clients one message truncated to the RFC-defined maximum length (512 bytes including CRLF).

**Comment by danieljabailey** [comment]
New, reproduceable trigger: https://runciman.hacksoc.org/~danieljabailey/long.html
