### ISSUE TITLE
Imgur plugin thinks new albums are NSFW

### ISSUE THREAD

**Issue by LordAro** [HackSoc/csbot#154]
```
[16:53:59] <LordAro> https://imgur.com/a/nS0h4dQ good morning
[16:54:00] -Mathison- [NSFW] Chimney ride 2019/05/27 (6 images)
```

![image](https://user-images.githubusercontent.com/4007992/58645621-9fbee200-82fb-11e9-8a38-e17d6e1e1f4a.png)

**Comment by LordAro** [comment]
Seems to only affect new albums? The below is run a few days later
```
17:02:36 < LordAro> @link https://imgur.com/a/nS0h4dQ
17:02:37 -LordAroBot:#cs-york-dev- Chimney ride 2019/05/27 (6 images)
17:02:43 < LordAro> huh.
17:04:17 < LordAro> https://imgur.com/a/ajrZ6Ul
17:04:17 -LordAroBot:#cs-york-dev- [NSFW] Test album (1 image)
```
putting a print statement in shows that whatever imgur is returning is definitely being parsed as a positive value:

>`{'id': 'ajrZ6Ul', 'title': 'Test album', 'description': None, 'datetime': 1559232241, 'cover': 'CgXloPY', 'cover_edited': None, 'cover_width': 860, 'cover_height': 1664, 'account_url': None, 'account_id': None, 'privacy': 'hidden', 'layout': 'blog', 'views': 0, 'link': 'https://imgur.com/a/ajrZ6Ul', 'favorite': False,` **'nsfw': True,** `'section': None, 'images_count': 1, 'in_gallery': False, 'is_ad': False, 'include_album_ads': False, 'is_album': True, 'images': [{'id': 'CgXloPY', 'title': None, 'description': None, 'datetime': 1559232242, 'type': 'image/png', 'animated': False, 'width': 860, 'height': 1664, 'size': 692199, 'views': 2, 'bandwidth': 1384398, 'vote': None, 'favorite': False, 'nsfw': None, 'section': None, 'account_url': None, 'account_id': None, 'is_ad': False, 'in_most_viral': False, 'has_sound': False, 'tags': [], 'ad_type': 0, 'ad_url': '', 'edited': '0', 'in_gallery': False, 'link': 'https://i.imgur.com/CgXloPY.png'}], 'ad_config': {'safeFlags': ['onsfw_mod_safe', 'share', 'page_load'], 'highRiskFlags': ['not_in_gallery'], 'unsafeFlags': ['updated_date'], 'showsAds': False}}`

(Note the `None` on the image itself)

**Comment by alanbriolat** [comment]
This is genuinely what the imgur API is saying about albums containing newly-uploaded images, so isn't a bug.
