### ISSUE TITLE
Error on exit with Python 3.6 - AttributeError: module 'asyncio' has no attribute 'all_tasks'

### ISSUE THREAD

**Issue by LordAro** [HackSoc/csbot#174]
Seems all_tasks was moved from asyncio.Tasks.all_tasks to asyncio.all_tasks in 3.7 - https://docs.python.org/3/whatsnew/3.7.html#asyncio (6th point)

Would be nice to keep 3.6 support for now...

**Comment by alanbriolat** [comment]
Python 3.6 compatibility promise dropped in #183.
