### ISSUE TITLE
Synchronous HTTP connections to slow/overloaded servers block the bot for too long

### ISSUE THREAD

**Issue by Haegin** [HackSoc/csbot#53]
## Steps to reproduce:
1. wait for haskell.org to be down (or DDoS haskell.org)
2. try using the !hoogle plugin
3. try using any other plugin
## Expected result

The hoogle plugin doesn't work and an error is printed. The other plugin works fine.
## Actual result

Mathison falls strangely silent then leaves the channel.

**Comment by alanbriolat** [comment]
This warrants revisiting now there is more asyncio magic threaded through the bot. We could reasonably implement timeouts, and theoretically it should be possible to handle IRC events asynchronously.

**Comment by alanbriolat** [comment]
As of #155, all bot events that make HTTP requests are asynchronous and wait in the background, allowing the bot to continue working. (`aiohttp` client has a default timeout of 5 minutes.)
