### ISSUE TITLE
Specify channel for !whois plugin

### ISSUE THREAD

**Issue by Helzibah** [HackSoc/csbot#66]
The whois plugin only works in the current channel at the moment.  It could do with an additional mode of specifying the channel so you can play in PM and not spam channels, e.g. `!whois Helzibah #cs-york` or `!whois.set #cs-york Fantastic`.

@Barrucadu

**Comment by LordAro** [comment]
Closedwontfix

```
16:10:53 < bjs> LordAro: also we're not doing issue66
16:11:18 < bjs> because either we'd need to force channel on each invokation (horrible) or make it context-sensitive (Alan said no before)
16:11:35 < bjs> i.e. !whois.set #python sucks
16:11:37 < bjs> should do what
```
